# Generated by Django 4.2 on 2023-06-30 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driverName', models.TextField(max_length=128)),
                ('driverID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('driverPhone', models.TextField(max_length=128)),
                ('driverEmail', models.EmailField(max_length=254)),
                ('driverPassword', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentName', models.TextField(max_length=128)),
                ('studentID', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('studentPhone', models.TextField(max_length=128)),
                ('studentEmail', models.EmailField(max_length=254)),
                ('studentPassword', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingNo', models.AutoField(primary_key=True, serialize=False)),
                ('bookingDate', models.DateField(blank=True, null=True)),
                ('bookingTime', models.TimeField(blank=True, null=True)),
                ('driverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VanBooking.driver')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VanBooking.student')),
            ],
        ),
    ]
